### ISSUE TITLE
Verbose Output During Release

### ISSUE THREAD

**Issue by bendbennett** [hashicorp/ghaction-terraform-provider-release#16]
## Overview
During a [release](https://github.com/hashicorp/terraform-provider-http/runs/7538909004?check_suite_focus=true) the `Promote` step failed with the following error:

```
Post "https://***/v1/releases/terraform-provider-http": context deadline exceeded
```

## Request
Would it be possible to modify the `Promote` phase so that there is more verbose logging of the individual steps that are taking place in order to surface which steps have completed successfully and which have not?

**Comment by bflad** [comment]
Given that these reusable workflows are calling out to other actions, I believe any logging improvements would need to be done to those actions. In particular for this error, I'm going to assume it came from https://github.com/hashicorp/actions-hc-releases-promote which handles the staging -> production Releases API portion of HashiCorp provider releases.

**Comment by bflad** [comment]
Hey @bendbennett 👋 Since I don't believe there is anything actionable in _this_ repository as I don't think we would want to manually re-implement the called action logic, I'm going to close out this issue. As suggested above, I would reach out in the called action repositories to submit feature requests around status output and we can ensure that these workflows use the upgraded actions if/when they are available.
